export const purchaseActionTypes = {
    PURCHASE_START: 'PURCHASE_START',
    PURCHASE_SUCCESS: 'PURCHASE_SUCCESS',
    PURCHASE_FAILURE: 'PURCHASE_FAILURE',
    PURCHASE_UPDATE:'PURCHASE_UPDATE',
    PURCHASE_UPDATE_SUCCESS:'PURCHASE_UPDATE_SUCCESS',
    PURCHASE_UPDATE_FAILURE:'PURCHASE_UPDATE_FAILURE',
};