export const profileActionTypes = {
    GET_PROFILE: 'GET_PROFILE',
    GET_PROFILESUCCESS: 'GET_PROFILE_SUCCESS',
    GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',
    UPDATE_PROFILE:'UPDATE_PROFILE',//saga action
    UPDATE_PROFILE_SUCCESS:'UPDATE_PROFILE_SUCCESS',//redux action
    UPDATE_PROFILE_FAILURE:'UPDATE_PROFILE_FAILURE',
};