export const userActionTypes = {
    USER_AUTH: 'USER_AUTH',
    SET_USER_PHONE: 'SET_USER_PHONE',
    USER_AUTH_SUCCESS: 'USER_AUTH_SUCCESS',
    USER_AUTH_FAILURE: 'USER_AUTH_FAILURE',
    USER_VERIFICATION: 'USER_VERIFICATION',
    USER_VERIFICATION_SUCCESS: 'USER_VERIFICATION_SUCCESS',
    USER_VERIFICATION_FAILURE: 'USER_VERIFICATION_FAILURE',
};