export const loanActionTypes = {
    UPDATE_LOAN_START: 'UPDATE_LOAN_START',
    UPDATE_LOAN_SUCCESS: 'UPDATE_LOAN_SUCCESS',
    UPDATE_LOAN_FAILURE: 'UPDATE_LOAN_FAILURE',
    UPDATE_LOAN_RESET: 'UPDATE_LOAN_RESET'
};